---
# This is the workday sensor. This binary sensor tells me if it is
# a workday  today.
#
# This is pretty useful for a lot of automations.
#
# https://www.home-assistant.io/integrations/workday/
#
- platform: workday
  name: worday
  country: NL
  workdays:
    - mon
    - tue
    - thu
    - fri
  excludes:
    - wed
    - sat
    - sun
    - holiday